/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 75f9a160ebc459bb3475df52912b59bd)
interface __BaseEnv_Env {
	MEALS: KVNamespace;
	DB: D1Database;
	PUSH_QUEUE: Queue;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
